# Generated by Django 2.2 on 2020-03-21 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=16)),
                ('image', models.ImageField(default='avatar.jpg', upload_to='img/agents')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
            },
        ),
        migrations.CreateModel(
            name='Main_Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(default='avatar.jpg', upload_to='img/Categories')),
            ],
            options={
                'verbose_name': 'Main_Category',
                'verbose_name_plural': 'Main_Categories',
            },
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(default='avatar.jpg', upload_to='img/Categories')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Main_Category')),
            ],
            options={
                'verbose_name': 'Sub_Category',
                'verbose_name_plural': 'Sub_Categories',
                'unique_together': {('main_category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('project_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cpanel.Contribution')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('city_1', models.CharField(blank=True, max_length=12, null=True)),
                ('country_1', models.CharField(blank=True, max_length=12, null=True)),
                ('apartment_no_1', models.CharField(blank=True, max_length=6, null=True)),
                ('building_1', models.CharField(blank=True, max_length=6, null=True)),
                ('Area_1', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_1', models.CharField(blank=True, max_length=16, null=True)),
                ('street_1', models.CharField(blank=True, max_length=30, null=True)),
                ('floor_1', models.CharField(blank=True, max_length=6, null=True)),
                ('Address_1', models.TextField(blank=True, null=True)),
                ('city_2', models.CharField(blank=True, max_length=12, null=True)),
                ('country_2', models.CharField(blank=True, max_length=12, null=True)),
                ('apartment_no_2', models.CharField(blank=True, max_length=6, null=True)),
                ('building_2', models.CharField(blank=True, max_length=6, null=True)),
                ('Area_2', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=16, null=True)),
                ('street_2', models.CharField(blank=True, max_length=30, null=True)),
                ('floor_2', models.CharField(blank=True, max_length=6, null=True)),
                ('Address_2', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('address_no', models.CharField(max_length=1)),
                ('assigned_agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Agent')),
                ('charitable_activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Sub_Category')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Contribution')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Donor')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('case_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cpanel.Contribution')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
            },
        ),
    ]
