# Generated by Django 2.2 on 2020-03-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='address_no',
            field=models.CharField(choices=[(1, 1), (2, 2)], max_length=1),
        ),
    ]
