# Generated by Django 2.2 on 2020-03-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0002_auto_20200321_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='address_no',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1),
        ),
    ]
