# Generated by Django 2.2 on 2020-03-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0005_auto_20200321_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['id'], 'verbose_name': 'Case', 'verbose_name_plural': 'Cases'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=models.ImageField(default='img/agents/avatar.jpg', upload_to='img/agents'),
        ),
        migrations.AlterField(
            model_name='case',
            name='code',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='image',
            field=models.ImageField(default='img/Categories/category.png', upload_to='img/Categories'),
        ),
    ]
