# Generated by Django 2.2 on 2020-03-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0007_auto_20200322_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['id'], 'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['id'], 'verbose_name': 'Contribution', 'verbose_name_plural': 'Contributions'},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['id'], 'verbose_name': 'Donor', 'verbose_name_plural': 'Donors'},
        ),
        migrations.AlterModelOptions(
            name='main_category',
            options={'ordering': ['id'], 'verbose_name': 'Main_Category', 'verbose_name_plural': 'Main_Categories'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['project_id'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='sub_category',
            options={'ordering': ['id'], 'verbose_name': 'Sub_Category', 'verbose_name_plural': 'Sub_Categories'},
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='Address_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='Address_2',
            new_name='address_2',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='Area_1',
            new_name='area_1',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='Area_2',
            new_name='area_2',
        ),
    ]
