# Generated by Django 2.2 on 2020-03-22 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0009_auto_20200322_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpanel.Agent'),
        ),
    ]
