# Generated by Django 2.2 on 2020-03-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0011_auto_20200325_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Our_Sponsor',
                'verbose_name_plural': 'Our_Sponsors',
            },
        ),
        migrations.CreateModel(
            name='Slider_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Slider_Image',
                'verbose_name_plural': 'Slider_Images',
            },
        ),
    ]
