# Generated by Django 2.2 on 2020-03-29 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0012_our_sponsor_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='Sub_Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpanel.Sub_Category'),
        ),
    ]
