# Generated by Django 2.2 on 2020-03-29 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0013_case_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Sub_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpanel.Sub_Category'),
        ),
    ]
