# Generated by Django 2.2 on 2020-03-29 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0014_auto_20200330_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['date'], 'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.RenameField(
            model_name='case',
            old_name='Sub_Category',
            new_name='sub_category',
        ),
    ]
